### ISSUE TITLE
`remove_redundant_nodes` leaves redundant nodes

### ISSUE THREAD

**Issue by Anaphory** [glottobank/python-newick#27]
When there are multiple leaves each with a singleton parent, `remove_redundant_nodes` skips some.

```
>>> import newick newick
>>> tree = newick.loads("((aiw),((aas,(kbt)),((abg),abf)))")[0]
>>> tree.remove_redundant_nodes()
>>> tree.newick
'(((aas,(kbt)),((abg),abf)),aiw:0.0)'
```

This should give

```
'(((aas,kbt),(abg,abf)),aiw:0.0)'
```

or something equivalent instead.

**Comment by Anaphory** [comment]
Looks like this issue comes from the fact that `remove_redundant_nodes` modifies the `descendants` list while `walk` is in the process of iterating over it. This has unforeseen consequences for the iteration.

It seems a simple copy of the list (in `walk()`, 

```
        for node in self.descendants[:]:
```

instead of 

```
        for node in self.descendants:
```

solves the issue for this particular tree. I will submit a pull request if it did not break any tests.

**Comment by lmaurits** [comment]
I'm a bit confused that this problem is supposedly fixed by using a copy of `self.descendants` inside `walk()`.  `remove_redundant_nodes` uses `walk(mode='postorder')`, which means that the `for` loop you modified isn't actually executed.  Instead the `_postorder()` method is used.  It seems likely a similar issue is happening here (i.e. changes in the descendant map are not recognised), but it will require a change to `_postorder` to fix it.
