### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by xrotwang** [glottobank/python-newick#9]
According to [Gary Olsen's interpretation of Newick](http://evolution.genetics.washington.edu/phylip/newick_doc.html), comments enclosed in square brackets may appear anywhere. We may want to support this, probably by stripping and ignoring the comments when parsing.

**Comment by xrotwang** [comment]
OTOH support for these comments by default introduces two more symbols `[]` which would be illegal in node names.

**Comment by xrotwang** [comment]
Maybe more importantly, `[]` in node labels is used for the [Glottolog](http://glottolog.org) newick files, to append glottocodes to the subgroup names. So maybe `strip_comments` should be an option, i.e. a boolean keyword argument for the parser, defaulting to `False` - and maybe set implicitly to `True` when parsing trees from Nexus files, see #7 .

**Comment by Anaphory** [comment]
I just stumbled over both sides of this issue. I am (still, like in #8) trying to a tree in a Nexus file in beastling, which contains comments – it actually starts with `[&R] (…` – and on the other hand, beastling uses glottolog as input, so my quick fix of adding a `strip_comments` function to `python-newick` made `beastling` fail with me.

So I vote for a `leave_comments=True` argument to `parse_node`, and passed through from above. (`leave_comments` because `strip_comments` looks like a good name for the function doing the actual heavy lifting.)

There is still a semantic question in stripping comments: Should `[a[b]c]d` become `c]d` or `d`? http://evolution.genetics.washington.edu/phylip/newick_doc.html only says that “PAUP (David Swofford) allows nesting of comments”, which by contrast might imply that Gary Olson considers that second way of handling comments the non-standard way. For the other one, this would be my implementation:

```
def remove_comments(s):
    """Remove comments from a Newick string.

    This function removes all substrings starting with an opening
    bracket `[` and ending with the next closing bracket `]` from the
    Newick string `s`.

    :param s: Newick formatted string to parse.
    :return: string.

    """
    while True:
        try:
            opening = s.index("[")
        except ValueError:
            return s
        try:
            closing = s.index("]", opening+1)
        except ValueError:
            raise ValueError('unmatched brackets %s' % s[opening:][:100])
        s = s[:opening]+s[closing+1:]

def parse_node(s, leave_comments=True, **kw):
    """
    Parse a Newick formatted string into a `Node` object.

    :param s: Newick formatted string to parse.
    :param kw: Keyword arguments are passed through to `Node.create`.
    :return: `Node` instance.
    """
    if not leave_comments:
        s = remove_comments(s)
    s = s.strip()
    parts = s.split(')')
    if len(parts) == 1:
        descendants, label = [], s
    else:
        if not parts[0].startswith('('):
            raise ValueError('unmatched braces %s' % parts[0][:100])
        descendants, label = list(_parse_siblings(')'.join(parts[:-1])[1:])), parts[-1]
    name, length = _parse_name_and_length(label)
    return Node.create(name=name, length=length, descendants=descendants, **kw)
```

**Comment by xrotwang** [comment]
@Anaphory I chose a simple regex-based implementation to strip the comments. Please have a look at the PR https://github.com/glottobank/python-newick/pull/21
